export const GET_PRIME_NUMBER = "GET_PRIME_NUMBER";
export const ARRAY_PRIME_NUMBER = "ARRAY_PRIME_NUMBER";
export const POST_PRIME_NUMBER = "POST_PRIME_NUMBER";
export const DELETE_ALL_NUMBER = "DELETE_ALL_NUMBER";
export const LOADING = "LOADING";
